### PR TITLE
Add compatibility for PolarDB/Ganos

### PR DESCRIPTION
**Pull request by erchen-cz**
# 1. Introduction
[PolarDB for PostgreSQL](https://www.alibabacloud.com/help/en/polardb-for-postgresql) (hereafter simplified as PolarDB) is a cloud native database service independently developed by Alibaba Cloud. PolarDB is 100% compatible with PostgreSQL. 

[Ganos](https://www.alibabacloud.com/help/en/polardb-for-postgresql/latest/spatio-temporal-database) adds rich build-in extensions to PolarDB, which empowers PolarDB the capability of managing spatio-temperal data such as raster and trajectory. Ganos is highly compatible with PostGIS by supporting the geometry data type and the functions of PostGIS.

Some customers of PolarDB are interested in using 3DCityDB on PolarDB and Ganos, and this test is to check if 3DCityDB can work with PolarDB and Ganos correctly.
# 2. How It Works
We use [citygml-change-detection](https://github.com/tum-gis/citygml-change-detection) to verify whether 3DCityDB is compatiable with PolarDB/Ganos by comparing its result with the result produced by PostgresSQL/PostGIS:

1. Import the test data into PostgreSQL/PostGIS using [3D City Database Importer/Exporter](https://github.com/3dcitydb/importer-exporter), and then export them to CityGML.
1. Import the same set of data into PolarDB/Ganos, and then export them to CityGML as well.
1. Use citygml-change-detection to show the different between the two sets of CityGML data .

If the comparison shows no difference, we can conclude that PolarDB/Ganos can replace PostgresSQL/PostGIS to work with 3DCityDB.
# 3. Modification
There is only one modification needed for adopting PolarDB/Ganos. Ganos implements a raster module and provides a native data type called raster. The following SQL sentences show how to support raster data in PostGIS and Ganos, respectively, where PostGIS needs to defines an extension while Ganos provides raster data natively.

```sql
SELECT EXISTS(SELECT 1 AS create_raster FROM pg_extension WHERE extname = 'postgis_raster') AS postgis_raster_exists;
SELECT CASE WHEN :'postgis_version' < '3' OR :'postgis_raster_exists' = 't'
...
```
-->
```sql
SELECT EXISTS(SELECT 1 AS create_raster from pg_type where typname= 'raster') AS raster_type_exists;
SELECT CASE WHEN :'raster_type_exists' = 't'
...
```
# 4. Result
The following datasets are used for the test：

- From [awesome-citygml](https://github.com/OloOcki/awesome-citygml):
   - Melbourne_Footpath_CityGML
   - LoD1_freiburg_25832
   - Hannover:
      - 5490_5801
      - 5500_5802
   - Hokota_54401379_fld_6697_l1_op
   - Random3Dcity:
      - LOD1_3_F0_H3
      - LOD3_3
- From [importer-exporter samples](https://github.com/3dcitydb/importer-exporter/tree/master/resources/samples):
   - Railway_Scene_LoD3
   - Berlin_Gasometer_LoD2
   - TUM Munich
   - Potsdam_LoD1

**The results on all the datasets show no difference between the outputs of PostgreSQL/PostGIS and PolarDB/Ganos. Therefore, the test demonstrates the correctness of using PolarDB/Ganos to work with 3DCityDB.**
# Appendix. Code and Script
We use container technique to build an easy-to-use test case, which requires the following files:
```shell
.
├── Dockerfile
├── app.js
└── docker-compose.yml
```
**NOTE: Docker and docker-compose are required for the test case.**
## 1 Dockerfile
We build a docker image with the following functions:

- Initialiaze 3DCityDB schema.
- Import/Export CityGML data.
- Detect changes between different CityGML data.
```dockerfile
FROM 3dcitydb/impexp:5.2.0-alpine

USER root
RUN apk add --no-cache git nodejs postgresql-client openjdk8

# get and set 3dcitydb sql
WORKDIR /
RUN git clone --depth 1 https://github.com/3dcitydb/3dcitydb

# copy and set citygml-change-detection
WORKDIR /citygml-change-detection
COPY --from=sonnguyentum/citygml-change-detection:0.2.0 /citygml-change-detection/citygml-change-detection.jar ./citygml-change-detection.jar
COPY --from=sonnguyentum/citygml-change-detection:0.2.0 /citygml-change-detection/citygml-change-detection_lib ./citygml-change-detection_lib
RUN mkdir ./input && mkdir ./config

COPY ./app.js /app.js

WORKDIR /data
ENTRYPOINT [ ]
CMD ["node","/app.js"]
```
## 2 app.js
Script node.js is the core of the test case. It conducts the following operations:

1. Copy the test datasets into a specified directory.
1. Perform the following procedures in turn for each dataset:
   1. Initialize 3DCityDB schema by executing SQL scripts.
   1. Import the data into PostgreSQL/PostGIS and then export them to CityGML.
   1. Import the data into PolarDB/Ganos and then export them to CityGML.
   1. Run citygml-change-detection to obtain the CSV reports of comparing the two results.
   1. Verify whether there is any change between them.
   1. Clear all temporary files and prepare the next comparison.
3. Clear all temporary files and drop the 3DCityDB schema.
```javascript
const { spawn, spawnSync } = require('child_process'),
  assert = require('assert'),
  { readdirSync, } = require('fs'),
  { join, extname } = require('path');

const { CITYGML_SRS, CITYGML_HEIGHT } = process.env,
  CWD = "/data",
  SQL_DIR = '/3dcitydb/postgresql/SQLScripts',
  CCD_DIR = '/citygml-change-detection';

const get_postgis_connect = () => {
  const { PG_HOST: host, PG_PORT: port, PG_USER: user, PG_DB: db, PG_PWD: pwd } = process.env;
  return { host, db, user, port, pwd };
};

const get_ganos_connect = () => {
  const { GANOS_HOST: host, GANOS_PORT: port, GANOS_USER: user, GANOS_DB: db } = process.env;
  return { host, db, user, port };
};

// command executor with promise wrapper
const commander = (command, args, env = {}) =>
  new Promise((res, rej) =>
    spawn(command, args, { env: { ...env, ...process.env } })
      .on('exit', (code, signal) => (!!code || signal ? rej(code || signal) : res()))
      .on('error', (err) => rej(err))
      .stderr.on('data', (data) => rej(data.toString())
      ));

const init_db = async (connection, only_clear = false) => {
  // 1. set connect info
  const { host, port, user, db, pwd: PGPASSWORD } = connection;
  const conn_args = ['-h', host, '-p', port, '-U', user, '-d', db];
  const env = PGPASSWORD ? { PGPASSWORD } : null;

  // 2. drop exists table first
  const drop_db_args = ['-f', `${SQL_DIR}/DROP_DB.sql`];
  await commander('psql', [...conn_args, ...drop_db_args], env);
  if (only_clear) return;

  // 3. create 3dcitydb schema
  const gmlsrsname = CITYGML_HEIGHT != 0 ?
    `gmlsrsname=urn:ogc:def:crs,crs:EPSG::${CITYGML_SRS},crs:EPSG::${CITYGML_HEIGHT}` :
    `gmlsrsname=urn:ogc:def:crs:EPSG::${CITYGML_SRS}`;
  const create_db_args = ['-f', `${SQL_DIR}/CREATE_DB.sql`, '-v', `srsno=${CITYGML_SRS}`, '-v', gmlsrsname];
  await commander('psql', [...conn_args, ...create_db_args], env);
};

const import_and_export_data = async (connection, source_path, result_path) => {
  const { host, port, user, db, pwd } = connection;
  const conn_args = ['-H', host, '-P', port, '-u', user, '-d', db, '-p', pwd];

  // 1. import data
  await commander('impexp', ['import', ...conn_args, source_path]);

  // 2. export data to specified path
  const export_args = ['export', ...conn_args, '-o', result_path];
  await commander('impexp', export_args);
};

const validate_result = async (postgis_result, ganos_result) => {
  // 1. write citygml-change-detection(ccd) config
  const config_path = join(CCD_DIR, './config', './config.txt');
  spawnSync('echo', [`OLD_CITY_MODEL_LOCATION=${postgis_result} >> ${config_path}`], { shell: true })
  spawnSync('echo', [`NEW_CITY_MODEL_LOCATION=${ganos_result} >> ${config_path}`], { shell: true })

  // 2. excute ccd
  const ccd_path = join(CCD_DIR, './citygml-change-detection.jar');
  const ccd_args = ['-jar', ccd_path, `-SETTINGS=${config_path}`];

  // set jdk-1.8 as default before running ccd
  const JDK8_HOME = '/usr/lib/jvm/java-1.8-openjdk'
  spawnSync('java', ccd_args, {
    cwd: '/citygml-change-detection',
    env: {
      "JAVA_HOME": JDK8_HOME,
      "PATH": `${JDK8_HOME}/bin:${process.env['path']}`,
      "CLASSPATH": `.:${JDK8_HOME}/lib/dt.jar:${JDK8_HOME}/lib/tools.jar`
    }
  });

  // 3. validate changes in csv report
  const cwd = join(CCD_DIR, './output');

  // there won't be any words in every csv-report if no changes between ganos and postgis result
  const { stdout } = spawnSync('tail', ['-n+2', '-q', '*.csv', '|', 'head', '-n1'], { cwd });
  assert(stdout.toString().length == 0, 'Error: Ganos result is different from postgis result.');

  // 4. clear workspace
  spawnSync('rm', ['-rf', 'neo4jDB', 'output', 'logs', 'config/*', 'input/*'], { cwd: CCD_DIR })
};

const validate_citygml = async (gml_path) => {
  // 1. get result from postgis
  const POSTGIS_CONNECT = get_postgis_connect();
  await init_db(POSTGIS_CONNECT);
  const postgis_result = join('/citygml-change-detection/input', './postgis_reult.gml');
  await import_and_export_data(POSTGIS_CONNECT, gml_path, postgis_result);

  // 2. get result from ganos
  const GANOS_CONNECT = get_ganos_connect();
  await init_db(GANOS_CONNECT);
  const ganos_result = join('/citygml-change-detection/input', './ganos_reult.gml');
  await import_and_export_data(GANOS_CONNECT, gml_path, ganos_result);

  // 3. validate result consistency between ganos and postgis
  await validate_result(postgis_result, ganos_result);
}

// main
(async () => {
  // 1. get all gmls as test data
  const datas = readdirSync(CWD).filter((v) => extname(v).toLocaleLowerCase() == '.gml');
  assert(datas.length > 0, `Error: No *.gml file in '/data'.`);

  // 2. validate compatibility in sequence
  for (let data of datas)
    await validate_citygml(join(CWD, data))
})().catch((error) => (console.log((error = error.message || error)) || error))
  .then(async (err) => {
    // 1. clear workspace after all
    spawnSync('rm', ['-rf', 'neo4jDB', 'output', 'logs', 'config/*', 'input/*'], { cwd: CCD_DIR })

    // 2. drop useless citydb schema
    await init_db(get_postgis_connect(), true);
    await init_db(get_ganos_connect(), true);

    if (err) process.exit(1)
  }).catch(() => { /* ignore connect error */ })
```
## 3 docker-compose.yml
We use docker-compose to make configuration settings more convenient.
```yaml
version: "3"

services:
  ganos_compatibility_test:
    build: ./
    image: ganos_compatibility_tester
    volumes:
      - ./test_data:/data
    environment:
      - GANOS_HOST=${GANOS_HOST}
      - GANOS_PORT=${GANOS_PORT-1922}
      - GANOS_USER=${GANOS_USER-polardb}
      - GANOS_DB=${GANOS_DB-3dcitydb}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT-5432}
      - PG_USER=${PG_USER-postgres}
      - PG_DB=${PG_DB-postgres}
      - PG_PWD=${PG_PWD-postgres}
      - CITYGML_SRS=${CITYGML_SRS-3857}
      - CITYGML_HEIGHT=${CITYGML_HEIGHT-0}
```
All parameters are of the literal type, and some have dafault values.
## 4. Bulding and Running

1. Set missing connection parameters as environment variables:
```shell
export GANOS_HOST=YOUR_GANOS_HOST
export PG_HOST=YOUR_POSTGRESQL_HOST
...
```

2. Copy the test datasets to a specified directory:
```shell
mkdir ./test_data 
cp [YOUR_TEST_DATA.gml] ./test_data/
cp [ANOTHER_TEST_DATA.gml] ./test_data/
...
```
**NOTE: Data should be in .gml format.**

3. Build the image and run the container:
```shell
docker-compose up --build
```

4. Container will be exited with code 0 if there is no difference between any pair of Ganos and PostGIS results. Otherwise, the code will be 1.

### CODE REVIEW

**Comment by Son-HNguyen** [comment]
Thank you for the PR and also for using our tool [citygml-change-detection](https://github.com/tum-gis/citygml-change-detection). Please note that currently this tool can only map and match CityGML buildings. If your datasets have e.g. bridges, tunnels, etc., then they will not be mapped and thus not matched. Support for other types of top-level features in CityGML will be published in the future releases. Please let me know if you have any question regarding the mapping and matching. Thanks again for your work.

**Comment by erchen-cz** [comment]
Thanks for comments.  This tool was introduced by @yaozhihang and used for comparing with PostGIS.  
> Support for other types of top-level features in CityGML will be published in the future releases
Hope to use this tool instead of [citygml-change-detection](https://github.com/tum-gis/citygml-change-detection) for compatibility testing.

**Review by yaozhihang — APPROVED** [review]
Thanks @erchen-cz.  Good work!

**Comment by erchen-cz** [comment]
Can anyone help to merge this PR?

**Pull request merged**
