### PR TITLE
drop minor versions and use badges instead

### PR DESCRIPTION
**Pull request by BWibo**
The version tables on the Docker pages needed to be maintained for each release. This PR drops minor versions from the table and uses badges that link to Github and DockerHub instead.
In the future, the tables need manual updating only for major releases.

grafik

### CODE REVIEW

**Comment by BWibo** [comment]
The badges will ofcourse always show the latest version.

**Comment by yaozhihang** [comment]
@BWibo thanks. One inconsist thing is that the minor version 4.1 of the 3DCityDB is still in the table. The question is how about keeping minor versions, and not putting patch versions into the tables?

**Comment by BWibo** [comment]
@yaozhihang That's right, I noticed that too. This is the case, because the Docker build workflows were released after `v4.0.0`. 
We can either put a note that this is the first Docker release. Another option would be I manually build a `v4.0.0` version and push it to Dockerhub and fix the table accordingly?

**Comment by BWibo** [comment]
@yaozhihang I proceeded and added v4.0.0 and v4.1.0 images to DockerHub for 3DCityDB (see https://hub.docker.com/r/3dcitydb/3dcitydb-pg/tags). Furthermore, I reworked the note in the docs a little and fixed the 3DCityDB table for v4.0.0.

**Review by yaozhihang — APPROVED** [review]
looks very good

**Review by clausnagel — APPROVED** [review]

**Pull request merged**
