### PR TITLE
Add copybutton to code boxes

### PR DESCRIPTION
**Pull request by BWibo**
This adds a handy copy button to code boxes, https://sphinx-copybutton.readthedocs.io/en/latest/.

There are some nice features:

* Copy code with one click.

* Copy only *command* and not the *command output* in a code box. For instance, in the example below this would copy only the command, which is indicated e.g. by a leading `$` sign. That allows for code examples that can be copied even if there output is given in the same code box.

  ```javascript
   $ console.log('Hello world')
   
   Hello World
  ```

Here is an example page we built using a github workflow, this [image](https://hub.docker.com/r/bwibo/sphinx-rtd) and Github pages:  https://tum-gis.github.io/gi-uebungen/00-template/index.html

@clausnagel  Can you please create a build for this PR for testing on readthedocs.io.
I have only used this with rSt/Sphinx docus I build on my own and want to see if this works on the RTD platform as well.

- [ ] Check, if this work on readthedocs.io
- [ ] Check, how this influences PDF/Latex exports.

### CODE REVIEW

**Comment by clausnagel** [comment]
@BWibo, building on readthedocs.io fails with the error messages posted below. I am not an expert here and don't know how to solve this.

```
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/3dcitydb-docs/envs/copybutton/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'sphinx_copybutton'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/3dcitydb-docs/envs/copybutton/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/3dcitydb-docs/envs/copybutton/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/3dcitydb-docs/envs/copybutton/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/3dcitydb-docs/envs/copybutton/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx_copybutton (exception: No module named 'sphinx_copybutton')

Extension error:
Could not import extension sphinx_copybutton (exception: No module named 'sphinx_copybutton')
```

**Comment by BWibo** [comment]
I added `sphinx-copybutton` to Python requirements and it seems to work.
Here you can take a look: https://3dcitydb-docs.readthedocs.io/en/copybutton/

**Comment by BWibo** [comment]
Before we merge, we should take a look at the configuration of this: https://sphinx-copybutton.readthedocs.io/en/latest/#customization

* Configure input prompt behavior: https://sphinx-copybutton.readthedocs.io/en/latest/#customization
  * What strings indicate an input prompt? This depends on what langauges we use in the docs.
    The RegEx below is what I currently use, mostly for Shell prompts indicated by a `$`. This should be fine for now an can be extened whenever needed.
    ```python
    copybutton_prompt_text = r">>> |\.\.\. |\$\s*|In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
    copybutton_prompt_is_regexp = True
    ```
  * Do we want to support line continuation characters? I suggest yes, as we have some boxes using line continuation.
     ```python
     copybutton_line_continuation_character = "\\"
     ```

**Comment by clausnagel** [comment]
Nice, @BWibo, and thanks for sorting this out.

**Review by clausnagel — APPROVED** [review]

**Comment by clausnagel** [comment]
Well, I think using `$` as prompt and `\` as line continuation sounds very reasonable and should already cover most of our examples. I think we have few examples where we use the Windows-style line continuation `^`, right? Do we need to adapt them or can we leave them as they are?

**Comment by BWibo** [comment]
I just searched the Docs for `^`. Currently, we don't have any code boxes using this line continuation char. 
So there is nothing we need to change right now. 

I just found one hint that `\` is to be replaced by `^` for Windows. For consistency it makes sence not to use both `^` and `\` in the docs, so let's stick to `\`.

**Comment by clausnagel** [comment]
Thanks for checking, @BWibo. Yes, I agree with your proposal to stick to `\` in our examples. I think we are ready to merge then. @yaozhihang will also take a look at the PR, so waiting for his review before actually merging.

**Comment by BWibo** [comment]
@yaozhihang Hey there, can we merge this?

**Review by yaozhihang — APPROVED** [review]
Thanks @BWibo All look good to me 👍

**Comment by BWibo** [comment]
@yaozhihang Cool, thx for review. I'll merge then.

**Pull request merged**
